services:
  initguard-app:
    build: .
    container_name: initguard-service
    restart: always
    # 只监听本地回环地址，外部防火墙开着也没关系，外面扫不到
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=initguard_db_pass
      - POSTGRES_HOST=db  # 对应下面的服务名
      - POSTGRES_PORT=5432
      - POSTGRES_DB=initguard
      - REDIS_HOST=redis  # 对应下面的服务名
      - REDIS_PORT=6379
      - REDIS_PASSWORD=initguard_redis_pass
      - SECRET_KEY=your_custom_secret_key_here
      - SUPERUSER_NAME=zhaoxi
      - SUPERUSER_EMAIL=zhaoxi@example.com
      - SUPERUSER_PASSWORD=admin_password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data:/app/data

  db:
    image: postgres:15-alpine
    container_name: initguard-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=initguard_db_pass
      - POSTGRES_DB=initguard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: initguard-redis
    command: redis-server --requirepass initguard_redis_pass
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "initguard_redis_pass", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5