[project]
name = "kubeguard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.26",
    "fastapi>=0.128.0",
    "loguru>=0.7.3",
    "passlib[bcrypt]>=1.7.4",
    "pyjwt>=2.11.0",
    "redis>=7.1.0",
    "sqlmodel>=0.0.31",
]
